name: azd-up
description: Packages, provisions and deploys the application to Azure

inputs:
  envName:
    description: The name of the environment to delete
    required: true
  environmentType:
    description: The type of environment to delete
    default: ""
  location:
    description: The Azure location
    required: true
    default: ${{ vars.AZURE_LOCATION }}
  subscriptionId:
    description: The Azure subscription id
    required: true
    default: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  tenantId:
    description: The Azure tenant id
    required: true
    default: ${{ vars.AZURE_TENANT_ID }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Package, Provision & Deploy Application
      run: azd up --no-prompt
      shell: bash
      env:
        AZURE_ENV_NAME: ${{ inputs.envName }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_TENANT_ID: ${{ inputs.tenantId }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscriptionId }}
        AZURE_DEVCENTER_ENVIRONMENT_TYPE: ${{ inputs.environmentType }}
