name: azd-up
description: Packages, provisions and deploys the application to Azure

inputs:
  envName:
    required: true
  environmentType:
    default: ""
  location:
    type: string
    required: true
    default: ${{ vars.AZURE_LOCATION }}
  subscriptionId:
    required: true
    default: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  tenantId:
    required: true
    default: ${{ vars.AZURE_TENANT_ID }}

runs:
  using: "composite"
  steps:
    - name: Package, Provision & Deploy Application
      run: azd up --no-prompt
      env:
        AZURE_ENV_NAME: ${{ inputs.envName }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_TENANT_ID: ${{ inputs.tenantId }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscriptionId }}
        AZURE_DEVCENTER_ENVIRONMENT_TYPE: ${{ inputs.environmentType }}
