name: azd-install

inputs:
  version:
    type: string
    required: false
    default: "daily"
runs:
  using: composite
  steps:
    - name: Install Azd
      run: |
        Invoke-RestMethod 'https://aka.ms/uninstall-azd.ps1' -OutFile 'uninstall-azd.ps1'; ./uninstall-azd.ps1 -Version '${{ inputs.version }}'
        Invoke-RestMethod 'https://aka.ms/install-azd.ps1' -OutFile 'install-azd.ps1'; ./install-azd.ps1 -Version '${{ inputs.version }}'
      shell: pwsh
