on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

# GitHub Actions workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config`

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  install-azd:
    uses: wbreza/azd-todo-ade/.github/workflows/azd-install.yml@reuseable-workflows
  login:
    uses: wbreza/azd-todo-ade/.github/workflows/azd-login.yml@reuseable-workflows
    with:
      clientId: ${{ vars.AZURE_CLIENT_ID }}
      tenantId: ${{ vars.AZURE_TENANT_ID }}
      subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
  up:
    uses: wbreza/azd-todo-ade/.github/workflows/azd-up.yml@reuseable-workflows
    with:
      envName: ${{ vars.AZURE_ENV_NAME }}-pr-${{ github.event.pull_request.number }}
      location: ${{ vars.AZURE_LOCATION }}
      subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      tenantId: ${{ vars.AZURE_TENANT_ID }}
      environmentType: Test